### ISSUE TITLE
Request: School logo URL and students_count

### ISSUE THREAD

**Issue by stephengade** [kaf-lamed-beyt/ng-universities#3]
First, this is a thoughtful project and I'm glad I can contribute.

Request:
- The school's logo is important for some use cases such as featuring the school on a page, in dropdown, etc
- students_count can be useful too maybe in data analytics etc.
- Would have suggested if possible to add the current vice-chancellor but that will request a request updating

**Comment by ajalapraise** [comment]
the logo and vice-chancellor is a very nice suggestion  buh for the students' count, it will be very hard unless we want to use an estimate which might not even be accurate eventually
Just my own POV tho

**Comment by kaf-lamed-beyt** [comment]
Thank you for these suggestions, @stephengade! 

Let's work with two &mdash; the current VC and the school's logo &mdash; of them for now, because we can't ascertain each school's total number of students. That'll require a lot of work. But hopefully, in the future, we can give it a shot.

I'll update the json schema to accommodate these changes!

**Comment by kaf-lamed-beyt** [comment]
I have one ask; 

Please feel free to share this repo with your folks who are in other schools across the federation, so they can also contribute. 

cc: @ajalapraise, @stephengade
